### ISSUE TITLE
Undefined method `strip` for nil:NilClass

### ISSUE THREAD

**Issue by ajfigueroa** [KrauseFx/mood#5] opened 2018-02-22 23:09 UTC
First off, I wanted to say that Mood has been pretty awesome so far.
Thank you for building it, I really enjoy using it 👍 

I noticed that my bot stopped responding after a bit so I checked out the Heroku logs and noticed that there was a crash. I'm unsure how this happened as it seemed like no invalid input was entered.

```
2018-02-22T17:29:52.170356+00:00 app[worker.1]: error sending the telegram notification
2018-02-22T17:29:52.170379+00:00 app[worker.1]: undefined method `strip' for nil:NilClass
2018-02-22T17:29:52.170381+00:00 app[worker.1]: /app/telegram_handler.rb:31:in `block (2 levels) in listen'
2018-02-22T17:29:52.170383+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:38:in `block in fetch_updates'
2018-02-22T17:29:52.170385+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:33:in `each'
2018-02-22T17:29:52.170386+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:33:in `fetch_updates'
2018-02-22T17:29:52.170388+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:25:in `listen'
2018-02-22T17:29:52.170389+00:00 app[worker.1]: /app/telegram_handler.rb:30:in `block in listen'
2018-02-22T17:29:52.170391+00:00 app[worker.1]: /app/telegram_handler.rb:85:in `perform_with_bot'
2018-02-22T17:29:52.170394+00:00 app[worker.1]: server.rb:3:in `<main>'
2018-02-22T17:29:52.170393+00:00 app[worker.1]: /app/telegram_handler.rb:29:in `listen'
```

This below screenshot is what I last entered prior to the responses stopping.
I added a small workaround to check for a nil `message.text` prior to parsing the input which happened at 1:32pm which seemed to resolve the issue. I'm curious to how this became nil though...

<img width="598" alt="screen shot 2018-02-22 at 6 03 45 pm" src="https://user-images.githubusercontent.com/3321592/36569192-cfcbc174-17fa-11e8-8e24-75f81ebbe093.png">

If you're accepting PRs, I can send a fix that checks if the text is not nil but otherwise I wanted to give a heads up.

**Comment by KrauseFx** [comment] 2018-02-23 00:47
Interesting, this never happened to me. Are you running it on the free Heroku tier?

**Comment by ajfigueroa** [comment] 2018-02-23 01:42
@KrauseFx Yes, I am running this on the free tier. I'll see if I can reproduce it again to see what exactly is happening.

**Comment by KrauseFx** [comment] 2018-02-24 22:50
It probably has something to do with the free tier then. I'll switch mine to the free tier also and see if I can reproduce

**Comment by KrauseFx** [comment] 2018-02-24 22:50
Oh actually I'm on the free tier also

**Comment by ajfigueroa** [comment] 2018-02-26 15:51
I ended up reverting my nil `message.text` check and I'll see if it happens again. However, since I don't know what triggered it initially I'm unsure how quickly it'll happen again.

**Comment by ajfigueroa** [comment] 2018-02-27 16:10
I was able to reproduce it but I'm unsure what exactly is going on. I'm attaching the full logs here in case there is more info here that I'm missing.
Note that `2018-02-26T15:46:24.116256+00:00` is when I deployed the reverting change mentioned in my previous [comment](https://github.com/KrauseFx/mood/issues/5#issuecomment-368548089).

The logs are a bit big so I've put it into a separate gist: https://gist.github.com/ajfigueroa/f392797db72ea2c3d662f1a05e625e19

**Comment by KrauseFx** [comment] 2019-02-19 05:51
This should be resolved, I'll close this for now

**Closed as completed by KrauseFx** 2019-02-19 05:51 UTC

**Comment by mitchellbusby** [comment] 2019-03-17 09:01
Is that because you do a nil check now @KrauseFx? 

I added a nil check in my fork and it seems to resolve the problem (I think this is a Telegram API thing not a Heroku thing) but never did a PR for it https://github.com/KrauseFx/mood/compare/master...mitchellbusby:master
